on: 
  workflow_call:
    inputs:
      # e.g. cr.daur-online.de/mdaur/build-container
      container-name-template:
        required: true
        type: string
      # e.g. linux/amd64,linux/arm64
      platforms:
        required: true
        type: string
      # TODO secrets

jobs:
  "Build Container":
    runs-on: ["docker","amd64"]
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     platform:
    #       - linux/amd64
    #       - linux/arm64

    container:
        # forgejo reference image with limitations e.g. docker cli missing
        #image: node:21-bullseye
        image: cr.daur-online.de/mdaur-amd64/build-container:v0.0.1
        # TODO container needs to present in dind, username password not used???
        username: ${{ secrets.REGISTRY_MDAUR_USER }}
        password: ${{ secrets.REGISTRY_MDAUR_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Tag Names
        id: tagNames
        run: |
          CNT="${{ inputs.container-name-template }}"
          TAGS="$CNT:nightly"
          TAGS="$TAGS,$CNT:${GITHUB_SHA::7}"
          [ "$GITHUB_REF_TYPE" = "tag" ] && TAGS="$TAGS,$CNT:${GITHUB_REF_NAME}"
          echo TAGS="${TAGS}" >> $GITHUB_OUTPUT

      - name: Test Tag Names
        run: |
          echo "tags=${{ steps.tagNames.outputs.TAGS }}"

      - name: Set up Docker Buildx (per architecture remote buildkit instance)
        id: setupBuilder
        uses: docker/setup-buildx-action@v3
        with:
          # ---
          # remote                -> self manager buildkit refered via endpoint(s)
          driver: remote
          # driver-opts: |
          #   key=KEY
          #   cert=CERT
          #   cacert=CACERT
          #   servername=SERVER
          # ---
          # docker-container      -> action managed buildkit container
          # driver: docker-container
          # driver-opts: |
          #   network=bridge
          endpoint: "tcp://bk.buildkit-amd64.svc.f24-10-int.daur-online.de:1234"
          platforms: linux/amd64
          append: |
            - endpoint: tcp://bk.buildkit-arm64.svc.f24-10-int.daur-online.de:1234
              platforms: linux/arm64
        env:
          # DOCKER_CERT_PATH: "/container/tls"
          # DOCKER_TLS_VERIFY: "true"
          # DOCKER_TLS: "true"
          # used for diver: remote # this means maintaining buildkit from scratch
          BUILDER_NODE_0_AUTH_TLS_CACERT: ${{ secrets.DIND_CA }}
          BUILDER_NODE_0_AUTH_TLS_CERT: ${{ secrets.DIND_CERT }}
          BUILDER_NODE_0_AUTH_TLS_KEY: ${{ secrets.DIND_KEY }}
          BUILDER_NODE_1_AUTH_TLS_CACERT: ${{ secrets.DIND_CA }}
          BUILDER_NODE_1_AUTH_TLS_CERT: ${{ secrets.DIND_CERT }}
          BUILDER_NODE_1_AUTH_TLS_KEY: ${{ secrets.DIND_KEY }}

      - name: Login to Registry
        # run: |
        #   [ ! -d $HOME/.docker ] && mkdir $HOME/.docker
        #   echo "${{ secrets.REGISTRY_MDAUR }}" > $HOME/.docker/config.json
        #   cat $HOME/.docker/config.json
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_MDAUR_URL }}
          username: ${{ secrets.REGISTRY_MDAUR_USER }}
          password: ${{ secrets.REGISTRY_MDAUR_PASSWORD }}

      - name: Build Multi Arch Container Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          #load: true     # requires docker socket/ config
          pull: true
          push: true
          # setting platforms will automatically select builder defined 
          # in step setupBuilder per architecture and build multi-arch image
          platforms: ${{ inputs.platforms }}
          tags: ${{ steps.tagNames.outputs.TAGS }}
          # bridge not supported by buildkit
          #network: bridge
          #outputs: type=docker,dest=/tmp/myimage.tar
          #endpoint:

      # not necessary in case docker/build-push-action and platforms input
      # manifest-tool combine images
      # - name: Push image to GHCR
      #   run: |
      #     docker buildx imagetools create \
      #       --tag ghcr.io/user/app:latest \
      #       --tag ghcr.io/user/app:1.0.0 \
      #       user/app:latest
