on:
  workflow_call:
    inputs:
      # e.g. mdaur/build-container
      container:
        required: true
        type: string
      # container-tag:
      #   required: true
      #   type: string

jobs:
  ScanContainer:
    runs-on: ["docker","amd64"]
    container:
      # forgejo reference image with limitations e.g. docker cli missing
      #image: node:21-bullseye
      image: cr.daur-online.de/mdaur/build-container:v0.0.11
      credentials:
        username: ${{ secrets.REGISTRY_MDAUR_USER }}
        password: ${{ secrets.REGISTRY_MDAUR_PASSWORD }}
      volumes:
        - "/container/run:/container/run"
    steps:
      - name: Setup trivy
        run: |
          docker volume create trivy-cache || /bin/true
          docker pull aquasec/trivy:latest

      - name: Commit SHA
        id: sha
        run: |
          SHA=${{github.SHA}}
          echo "SHA=${SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_MDAUR_URL }}
          username: ${{ secrets.REGISTRY_MDAUR_USER }}
          password: ${{ secrets.REGISTRY_MDAUR_PASSWORD }}

      # for caching and performance reason trivy action is not used
      - name: Scan container
        run: |
          IMAGE=cr.daur-online.de/${{ inputs.container-name }}:${{steps.sha.outputs.SHA}}
          docker pull $IMAGE
          set -o pipefail

          docker run \
            -v /container/run/docker.sock:/var/run/docker.sock \
            -v trivy-cache:/root/.cache/ aquasec/trivy:latest \
            image -s UNKNOWN,LOW,MEDIUM $IMAGE | tee trivy-report-medium.txt

          docker run \
            -v /container/run/docker.sock:/var/run/docker.sock \
            -v trivy-cache:/root/.cache/ aquasec/trivy:latest \
            image --exit-code 1 -s HIGH,CRITICAL $IMAGE | tee trivy-report-critical.txt        

      - name: Build trivy report        
        if: always()
        run: |
          cat trivy-report-critical.txt > trivy-report.txt
          cat trivy-report-medium.txt >> trivy-report.txt

      - name: Archive trivy report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report
          path: trivy-report.txt

      - name: Send telegram message
        uses: https://github.com/appleboy/telegram-action@master
        if: failure()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Security vulnerabilities found
            Repository: ${{ github.repository }}
            Job: ${{ github.job }}
            Result: https://scm.daur-online.de/${{ github.repository }}/actions/runs/${{ github.run_number }}
